In [10]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# Sample documents
documents = [
    "This is a list which containig sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings."
]
     
query="keyword-based search"

In [5]:
import re
def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = re.sub(r'[^\w\s]', '', text)
    return text


preprocess_documents=[preprocess_text(doc) for doc in documents]
     

preprocess_documents
     

print("Preprocessed Documents:")
for doc in preprocess_documents:
    print(doc)
     

print("Preprocessed Query:")
print(query)
     

preprocessed_query = preprocess_text(query)
     

preprocessed_query

Preprocessed Documents:
this is a list which containig sample documents
keywords are important for keywordbased search
document analysis involves extracting keywords
keywordbased search relies on sparse embeddings
Preprocessed Query:
keyword-based search


'keywordbased search'

In [6]:
vector=TfidfVectorizer()
x=vector.fit_transform(preprocess_documents)
array=x.toarray()

In [7]:
array

array([[0.        , 0.        , 0.37796447, 0.        , 0.37796447,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.37796447, 0.        , 0.        , 0.37796447, 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.37796447],
       [0.        , 0.4533864 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.4533864 , 0.4533864 , 0.        ,
        0.        , 0.35745504, 0.35745504, 0.        , 0.        ,
        0.        , 0.        , 0.35745504, 0.        , 0.        ,
        0.        ],
       [0.46516193, 0.        , 0.        , 0.46516193, 0.        ,
        0.        , 0.46516193, 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.36673901, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.43671931, 0.        , 0.        , 0.       

In [9]:
query_embedding=vector.transform([preprocessed_query])
query_embedding

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (1, 21)>

- BM25 is the updated part of TFIDF. TFIDF mainly focuses on keywoad frequency and not on semantic meaning and relationship. Useful when we want to heavily match exact words.
- These generate sparse Matrix
- measures the importance of a word in a document relative to an entire corpus. 
- Corpus refers to the complete data.
-It is a statistical method that is used to evaluate the importance of a word in a document. The TF-IDF approach calculates a score for each word in a document, which reflects its importance in that document.
- TF represents (# of times term comes in a text)/(# of terms in a text)
- IDF represents (# of texts in corpus)/(# of terms texts containing term t in a corpus)
- old method was using this TF x IDF to generate Vectors.
- Now we have vector search and all and here, we use transformers to create vectors from texts which are dense vectors and cosine similarity and all and can be performed on them.

# Keyword based search

In [12]:
similarities=cosine_similarity(x,query_embedding)
similarities

array([[0.        ],
       [0.50551777],
       [0.        ],
       [0.48693426]])

In [17]:
#Ranking
ranked_indices=np.argsort(similarities,axis=0)[::-1].flatten()
ranked_indices

array([1, 3, 2, 0])

In [ ]:
np.argsort(similarities,axis=0) #Here sorted indices based on similarities values
ranked_documents = [documents[i] for i in ranked_indices]
ranked_documents

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

# Using Vector Embeddings

In [18]:
from sentence_transformers import SentenceTransformer

/Users/nisargbhatia/Desktop/langGraph/RAG/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [26]:
model=SentenceTransformer("all-MiniLM-L6-v2")
embeddings=model.encode(preprocess_documents)
query_embedding2=model.encode(preprocessed_query).reshape(1,-1)

In [27]:
query_embedding2

array([[-9.34928749e-03, -5.88050708e-02, -2.40736175e-02,
         3.79789397e-02, -2.87498571e-02,  5.33267185e-02,
         7.13340044e-02,  1.72377639e-02, -3.33929881e-02,
         2.41078641e-02,  3.20847183e-02,  1.47228008e-02,
         1.21521279e-01, -3.62913236e-02, -2.07968317e-02,
         8.75071995e-03,  3.46281417e-02,  7.94901997e-02,
        -4.51725759e-02, -2.55422760e-02,  6.80354536e-02,
         4.36825939e-02,  2.13527214e-03, -2.71932054e-02,
        -2.38886811e-02,  3.39270160e-02, -7.04815388e-02,
        -8.11266899e-02,  4.06988561e-02,  3.02442219e-02,
         1.04071070e-02,  5.07700928e-02,  1.10834412e-01,
         1.57443434e-01,  1.31421750e-02, -2.32421532e-02,
        -5.89699410e-02,  4.43411581e-02, -1.04013309e-02,
         3.52705154e-03, -6.07758053e-02,  2.73566064e-03,
        -4.12737206e-02,  2.10162643e-02,  6.19455427e-02,
        -2.87003275e-02, -7.43091479e-02, -3.67941847e-03,
         1.60609223e-02,  5.68192126e-03, -1.07638039e-0

In [28]:
similarities2=cosine_similarity(embeddings,query_embedding2)
similarities2

array([[0.2384148],
       [0.885544 ],
       [0.5083779],
       [0.7863099]], dtype=float32)

In [29]:
#Ranking
ranked_indices2=np.argsort(similarities,axis=0)[::-1].flatten()
ranked_indices2

array([1, 3, 2, 0])

In [30]:
np.argsort(similarities,axis=0) #Here sorted indices based on similarities values
ranked_documents = [documents[i] for i in ranked_indices2]
ranked_documents

['Keywords are important for keyword-based search.',
 'Keyword-based search relies on sparse embeddings.',
 'Document analysis involves extracting keywords.',
 'This is a list which containig sample documents.']

However, cosine_similarity() expects a matrix of shape:

(number_of_samples, number_of_features)
for reshape (1,-1) --> 1 means 1 row
-1 means

"NumPy, you figure out this dimension automatically."

Since there are 384 values total, NumPy calculates

384 values
1 row
→ 384 columns